## 3.5 designing a function

This notebook reviews a bottom-up design process to create a Python function.  In this example, we want a function that will compute the roots for a sequence of quadratics where each quadratic is a row of a matrix and the three columns of the matrix are the three coefficients a, b, and c &ndash; as in ax&ast;&ast;2+bx+c = 0 &ndash; in that order.

After writing our pseudocode, we don't just translate it all into code and hope it works.  Better to build it line by line and see what we get (using print statements) before we add another line.

We start by writing a docstring to give us our objective in writing the function.

In [1]:
import numpy as np
def func(coeff_matrix):
    """Compute roots for an array of quadratic coefficients.
    
       Each quadratic is a row of `coeff_matrix`.  The three columns of
       `coeff_matrix` are the three coefficients a, b, and c corresponding
       to ax**2+bx+c = 0 in that order."""
    return root1, root2

That's it.  Start there.  Run it,... and get nothing, unless you have a syntax error.  (Did we forget the colon?  Do we have proper indentation?).

The next step has three additions steps:
<ul>
    <li>make the function return something clearly wrong;</li>
    <li>create some <u>short</u> but appropriate input data;</li>
    <li>print everything to make sure it's what we expect.</li>
    </ul>

In [ ]:
import numpy as np
def quadratic_roots(coeff_matrix):
    """Compute roots for an array of quadratic coefficents.
    
       Each quadratic is a row of `coeff_matrix`.  The three columns of
       `coeff_matrix` are the three coefficients a, b, and c corresponding
       to ax**2+bx+c = 0 in that order."""
    root1 = -888.888
    root2 = -999.999
    print("in function, root1, root2:", root1, root2)
    return root1, root2

coeff_matrix = np.array([[1., -2., 1.],   \
                         [1., -3., 1.],   \
                         [1., -4., 1.] ])
print("coeff_matrix =")
print(coeff_matrix)
print()
root1, root2 =  quadratic_roots(coeff_matrix)
print("root1, root2 = ", root1, root2)

The answer is wrong, of course, but at least we think we know what we're going for.  (This is not correct, as you may have already figured out, but let's stay with what we have and see where it goes.)

What we do know is that our syntax is correct, our test matrix is as expected, and we're printing things.

So now we add some code, a little at a time.  We start by creating the loop that will sequence through the rows of `coeff_matrix`.  Add print statements to verify <u>everything</u>, even the loop index to make sure we specified the start and stop for `range` correctly.

In [ ]:
import numpy as np
def quadratic_roots(coeff_matrix):
    """Compute roots for an array of quadratic coefficents.
    
       Each quadratic is a row of `coeff_matrix`.  The three columns of
       `coeff_matrix` are the three coefficients a, b, and c corresponding
       to ax**2+bx+c = 0 in that order."""
    eqns = coeff_matrix.shape[0]                     # NEW
    print("in function, eqns =", eqns)               # NEW
    for i in range(0, eqns):                         # NEW
        print("  LOOP", i)                           # NEW
        root1 = -888.888                             # indented
        root2 = -999.999                             # indented
        print("    ** root1, root2:", root1, root2)  # changed text
    return root1, root2

coeff_matrix = np.array([[1., -2., 1.],   \
                         [1., -3., 1.],   \
                         [1., -4., 1.] ])
print("coeff_matrix =")
print(coeff_matrix)
print()
root1, root2 =  quadratic_roots(coeff_matrix)
print("root 1, root 2 = ", root1, root2)

If you didn't notice before, now we see that something is not right.  We calculate three sets of roots, but only the last set is returned to be printed outside the function.  We need to return an array of roots, not scalars.

We add code to create the proper roots array, and set the roots to zero for now.  We remove the statements setting root1 and root2, and adjust the return statement and the print statement after the function call.

In [ ]:
import numpy as np
def quadratic_roots(coeff_matrix):
    """Compute roots for an array of quadratic coefficents.
    
       Each quadratic is a row of `coeff_matrix`.  The three columns of
       `coeff_matrix` are the three coefficients a, b, and c corresponding
       to ax**2+bx+c = 0 in that order."""
    eqns = coeff_matrix.shape[0]
    print("in function, eqns =", eqns)
    roots = np.zeros((eqns, 2))                             # NEW (notice required two sets of parentheses)
    print("in function, roots is initialized to\n", roots)  # NEW
    for i in range(0, eqns):
        print("  LOOP", i)
    return roots                                            # CHANGED

coeff_matrix = np.array([[1., -2., 1.],   \
                         [1., -3., 1.],   \
                         [1., -4., 1.] ])
print("coeff_matrix =")
print(coeff_matrix)
print()
roots =  quadratic_roots(coeff_matrix)                      # CHANGED
print()
print("Roots = \n", roots)                                  # CHANGED


Now add code to calculate just the discriminant.

In [ ]:
import numpy as np
def quadratic_roots(coeff_matrix):
    """Compute roots for an array of quadratic coefficents.
    
       Each quadratic is a row of `coeff_matrix`.  The three columns of
       `coeff_matrix` are the three coefficients a, b, and c corresponding
       to ax**2+bx+c = 0 in that order."""
    eqns = coeff_matrix.shape[0]
    print("in function, eqns =", eqns)
    roots = np.zeros((eqns, 2))
    print("in function, roots is initialized to\n", roots)
    for i in range(0, eqns):
        print("  LOOP", i)
        a, b, c = coeff_matrix[i, 0], coeff_matrix[i, 1], coeff_matrix[i, 2]   # NEW
        desc = np.sqrt(b**2 - 4*a*c)                                           # NEW
        print("      a, b, c =", a, b, c)                                      # NEW
        print("      discriminant =", desc)                                    # NEW
    return roots

coeff_matrix = np.array([[1., -2., 1.],   \
                         [1., -3., 1.],   \
                         [1., -4., 1.] ])
print("coeff_matrix =")
print(coeff_matrix)
print()
roots =  quadratic_roots(coeff_matrix)
print()
print("Roots = \n", roots)

Notice that we created the variables `a`, `b`, and `c` to make our subsequent expressions look more natural.  This can improve readability and helps in spotting typos in formulas.  Again, Python is a good tool for prototyping code; use the tool to help you build solutions.

If we are convinced that our initializion of `roots`, our new variable names, and our new discriminant statements work correctly, we can remove the associated print statements to reduce clutter so we can concentrate on what we need to check.  On the other hand, when we later test our function with coefficients that result in complex roots, we may need to add some print statements back in to see what's going on (if there's an error).

Now add in the root calculator.

In [ ]:
import numpy as np
def quadratic_roots(coeff_matrix):
    """Compute roots for an array of quadratic coefficents.
    
       Each quadratic is a row of `coeff_matrix`.  The three columns of
       `coeff_matrix` are the three coefficients a, b, and c corresponding
       to ax**2+bx+c = 0 in that order."""
    eqns = coeff_matrix.shape[0]
    print("in function, eqns =", eqns)
    roots = np.zeros((eqns, 2))
    print("in function, roots is initialized to\n", roots)
    for i in range(0, eqns):
        print("  LOOP", i)
        a, b, c = coeff_matrix[i, 0], coeff_matrix[i, 1], coeff_matrix[i, 2]
        desc = np.sqrt(b**2 - 4*a*c)
        print("      a, b, c =", a, b, c)
        print("      discriminant =", desc)
        roots[i, 0] = (-b + desc) / 2*a            # NEW
        roots[i, 1] = (-b - desc) / 2*a            # NEW
        print("      roots =\n", roots)            # NEW
    return roots

coeff_matrix = np.array([[1., -2., 1.],   \
                         [1., -3., 1.],   \
                         [1., -4., 1.] ])
print("coeff_matrix =")
print(coeff_matrix)
print()
roots =  quadratic_roots(coeff_matrix)
print()
print("Roots = \n", roots)

Did you spot the mistake?  The roots are the correct values, but the code is wrong.  We added only three lines, and it's not the third one (the print statement).  Can you spot the problem?
<br>
.
<br>
.
<br>
.
<br>

Test cases are only as good as they cover all possibilities.  In this case, the calculations are wrong because of precendence of operators:  you want to divide by the factor (2&ast;a), not divide by 2 and then multiply that result by a.

But in the test cases we always set a=1.0, so the error was never detected.  Again, debugging is both an art and a science.

The following code corrects the mistake, and gives the same results.

In [ ]:
import numpy as np
def quadratic_roots(coeff_matrix):
    """Compute roots for an array of quadratic coefficents.
    
       Each quadratic is a row of `coeff_matrix`.  The three columns of
       `coeff_matrix` are the three coefficients a, b, and c corresponding
       to ax**2+bx+c = 0 in that order."""
    eqns = coeff_matrix.shape[0]
    print("in function, eqns =", eqns)
    roots = np.zeros((eqns, 2))
    print("in function, roots is initialized to\n", roots)
    for i in range(0, eqns):
        print("  LOOP", i)
        a, b, c = coeff_matrix[i, 0], coeff_matrix[i, 1], coeff_matrix[i, 2]
        desc = np.sqrt(b**2 - 4*a*c)
        print("      a, b, c =", a, b, c)
        print("      discriminant =", desc)
        roots[i, 0] = (-b + desc) / (2*a)
        roots[i, 1] = (-b - desc) / (2*a)
        print("      roots =\n", roots)
    return roots

coeff_matrix = np.array([[1., -2., 1.],   \
                         [1., -3., 1.],   \
                         [1., -4., 1.] ])
print("coeff_matrix =")
print(coeff_matrix)
print()
roots =  quadratic_roots(coeff_matrix)
print()
print("Roots = \n", roots)

Finally, convinced that our function works, we:
<ul>
    <li>update our docstring to correspond to the final result;</li>
    <li>save our "instrumented" code as something like "quadratic_roots-instrumented.py"; and</li>
    <li>strip out all of the test code in our working version.</li>
    </ul>

In [2]:
import numpy as np
def quadratic_roots(coeff_matrix):
    """Compute roots for an array of quadratic coefficents.
    
       Each quadratic is represented by a row of `coeff_matrix`.  The three
       columns of `coeff_matrix` are the three coefficients a, b, and c
       corresponding to ax**2+bx+c = 0 in that order.
       
       The output is an array of roots with a row for each input row and
       two columns for the two roots, + then -.
       """
    eqns = coeff_matrix.shape[0]     # each row of `coeff_matrix` is a quadratic
    roots = np.zeros((eqns, 2))
    for i in range(0, eqns):
        a, b, c = coeff_matrix[i, 0], coeff_matrix[i, 1], coeff_matrix[i, 2]
        desc = np.sqrt(b**2 - 4*a*c)
        roots[i, 0] = (-b + desc) / (2*a)
        roots[i, 1] = (-b - desc) / (2*a)
    return roots

Submitty = False
if (not Submitty):
    coeff_matrix = np.array([[1., -2., 1.],   \
                             [1., -3., 1.],   \
                             [1., -4., 1.] ])
    print("coeff_matrix =")
    print(coeff_matrix)
    print()
    roots =  quadratic_roots(coeff_matrix)
    print("Roots = \n", roots)

coeff_matrix =
[[ 1. -2.  1.]
 [ 1. -3.  1.]
 [ 1. -4.  1.]]

Roots = 
 [[1.         1.        ]
 [2.61803399 0.38196601]
 [3.73205081 0.26794919]]
